import Tactic.Alias
import Tactic.Clear
import Tactic.Choose
import Tactic.Converter.ApplyCongr
import Tactic.Congr
import Tactic.DecTrivial
import Tactic.DeltaInstance
import Tactic.Dependencies
import Tactic.Elide
import Tactic.Explode
import Tactic.Find
import Tactic.Finish
import Tactic.Generalizes
import Tactic.GeneralizeProofs
import Tactic.ITauto
import Tactic.Lift
import Mathbin.Tactic.Lint.Default
import Tactic.Localized
import Tactic.MkIffOfInductiveProp
import Tactic.NormCast
import Tactic.Obviously
import Tactic.PrettyCases
import Tactic.PrintSorry
import Tactic.Protected
import Tactic.PushNeg
import Tactic.Replacer
import Tactic.RenameVar
import Tactic.RestateAxiom
import Tactic.Rewrite
import Tactic.ShowTerm
import Tactic.SimpRw
import Tactic.SimpCommand
import Tactic.SimpResult
import Tactic.Simps
import Tactic.SplitIfs
import Tactic.Squeeze
import Tactic.Suggest
import Tactic.Tauto
import Tactic.TruncCases
import Tactic.UnifyEquations
import Tactic.Where

#align_import tactic.basic from "leanprover-community/mathlib"@"3536f47529aaf55f56b1fd9c177dee648d26b0a1"

